### ISSUE TITLE
Lost connection to MYSQL server when starting mfrun users

### ISSUE THREAD

**Issue by CesMak** [miguelgrinberg/microflack_users#5]
Hey there,

I am not that familiar yet with mysql-clients, maybe someone can help me:

I got these errors when trying to ./mfrun users or ./mfrun messages:

## Error
```
Do mfrun users 
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 22

# or 
Do mfrun users 
ERROR 1045 (28000): Access denied for user 'root'@'172.17.0.1' (using password: YES)
```

## Reproducing the error:
0. Having mysql-data-dir available (installed) as well as the wheels folder
1. Run following containers:
```
ui_cecc2874e853
lb 
redis
mysql
etcd
logspout
```
2. If I then do ./mfrun messages or ./mfrun users I sometimes get the above error. 

Any advice why I cannot access?

**Comment by miguelgrinberg** [comment]
I don't know what error 22 is, but have you given enough time to the mysql container to start up?
